<?php

declare(strict_types=1);

namespace App\Amqp\Producer;

use Hyperf\Amqp\Annotation\Producer;
use Hyperf\Amqp\Message\ProducerMessage;

/**
 * @Producer(exchange="hyperf", routingKey="hyperf")
 */
class DanmuProducer extends ProducerMessage
{
    public function __construct($data)
    {
        $this->payload = $data;
    }

    public function setPayload($data) : ProducerMessage
    {
        return parent::setPayload($data); // TODO: Change the autogenerated stub
    }
}
